name: build

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14.3.0-alpine

    steps:
      - uses: actions/checkout@v2

      - name: dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: lint
        run: npm run lint

      - name: audit
        run: npm audit

      - name: test:coverage
        run: npm run test:coverage

      - name: test:integration
        run: npm run test:integration

      - name: Archive Coverage Results
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: dist/coverage
