name: Build

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v2
      - uses: ./github/actions/run-in-docker

      - name: dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: lint
        run: npm run lint

      - name: audit
        run: npm audit --registry=https://registry.npmjs.org

      - name: test:coverage
        run: npm run test:coverage

      - name: test:integration
        run: npm run test:integration
