name: Bump Version

on: push

jobs:
  npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: ''
