name: Publish Public Docker Image to DockerHub

on:
  push:
    branches:
      - master

jobs:
  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: publish docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: diegoh/koa-mock-api
          tags: ${{ steps.package-version.outputs.current-version}}
