name: publish

on:
  push:
    branches-ignore:
      - master

jobs:
  npm-public:
    runs-on: ubuntu-latest
    container:
      image: node:14.3.0-alpine

    steps:
      - uses: actions/checkout@v2

      - name: publish npm
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  dockerhub-public:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: publish docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: diegoh/koa-mock-api
          tags: ${{ steps.package-version.outputs.current-version}}
